Add configurable lambda ephemeral storage size
trussworks/terraform-aws-s3-anti-virus pull request #36
Opened 2022-06-01 16:16 UTC by aleskovets

Adds support for configuring lambda storage size. Useful if scanning for large files is required. https://aws.amazon.com/blogs/aws/aws-lambda-now-supports-up-to-10-gb-ephemeral-storage

2022-08-16 16:40 UTC, aleskovets commented
@chtakahashi, @nyanbinaryneko , hey! is there anything that I should change in PR or PRs are generally are not accepted top to this repo?

2022-10-27 18:58 UTC, rpdelaney requested changes
Thanks! I left some comments

2022-10-27 18:58 UTC, rpdelaney commented on variables.tf
> +  default     = 512
Would this benefit from [validation](https://developer.hashicorp.com/terraform/language/values/variables#custom-validation-rules) at the module level or will invalid values result in a plan failure?

2022-10-27 18:58 UTC, rpdelaney commented on versions.tf
> +    aws = ">= 4.9.0"
nit: It looks like `ephemeral_storage` was added in 4.8? [[1]](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#user-content-480-march-25-2022)

2022-10-27 18:58 UTC, rpdelaney commented on anti-virus-scan.tf
> +    size = var.ephemeral_storage_size # Min 512 MB and the Max 10240 MB
```suggestion
    size = var.ephemeral_storage_size
```

2023-02-06 15:41 UTC, rpdelaney commented
@aleskovets Please feel free to re-open if you still need this!

2023-02-06 15:41 UTC, closed without merging